global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "rvault"
    scrape_interval: 1s
    static_configs:
      - targets: ["storage-rvault:9200"]
    metrics_path: "/metrics"
    scheme: "http"
