version: "3.8"

services:
  mongodb:
    container_name: mongodb-rvault
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./rvault_data/mongodb:/data/db
    networks:
      - mongo_net

  redis:
    container_name: redis-rvault
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=simple_redis_password
    ports:
      - "6379:6379"
    volumes:
      - ./rvault_data/redis:/data
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
